### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by sdroege**
See the individual commits for details

### CODE REVIEW

**Comment by sdroege** [comment]
This fixes https://github.com/drizzt/gladstone/issues/3 and https://github.com/drizzt/gladstone/issues/2 as a side-effect.

**Comment by lemenkov** [comment]
Still cannot decode raw g729 with these patches.
This works (I guess any mono 8khz wav-filess will work):

```shell
gst-launch-1.0 filesrc location=./eng_f7.wav ! wavparse ! g729enc ! g729dec ! audioresample ! pulsesink
```

This also works (the resulting `./test.g729` file is playable with mpv):

```shell
gst-launch-1.0 filesrc location=./eng_f7.wav ! wavparse  ! g729enc ! filesink location=./test.g729
```

But this one doesn't work for me:

```shell
gst-launch-1.0 filesrc location=./test.g729 ! "audio/G729,rate=(int)8000,channels=(int)1" ! g729dec ! filesink location=./test.raw
```

Maybe I'm missing something?

**Comment by sdroege** [comment]
You can't decode raw g729, that's correct. It needs to be properly packetized, e.g. from RTP or some other container format (not WAV). A parser would be needed otherwise first, but that doesn't exist currently.

**Comment by lemenkov** [comment]
> You can't decode raw g729, that's correct. It needs to be properly packetized, e.g. from RTP or some other container format (not WAV). A parser would be needed otherwise first, but that doesn't exist currently.

Ah got that.
For raw G729a stream it should be as simple as slicing incoming stream by 10 bytes. Is it possible with currently existing Gstreamer filters? I mean maybe there is some kind of setting for filesrc which lets it to write data only by packets of a given size.

**Comment by sdroege** [comment]
Not without writing code for that, and as you can see from the code here the G729 packets can be different sizes than 10 so you'd need to write a proper parser instead of just chunking into 10 byte packets.

Where did you get unframed G729 packets from?

**Pull request merged**
